.include <src.opts.mk>

OS!=	uname -s

SRCS=	cheriostest.c

SRCS+=	cheriostest_bounds_globals.c					\
	cheriostest_util.c \
	cheriostest_util_vm.c						\
	cheriostest_bounds_globals_x.c					\
	cheriostest_bounds_heap.c					\
	cheriostest_bounds_stack.c					\
	cheriostest_cidcap.c						\
	cheriostest_context.c						\
	cheriostest_fault.c	\
	cheriostest_flag_captured.c					\
	cheriostest_fs.c						\
	cheriostest_kbounce.c						\
	cheriostest_internal.c 					\
	cheriostest_ipc.c				\
	cheriostest_local_global.c					\
	cheriostest_longjmp.c						\
	cheriostest_printf.c						\
	cheriostest_ptrace.c			\
	cheriostest_registers.c		\
	cheriostest_sealcap.c			\
	cheriostest_signal.c						\
	cheriostest_string.c						\
	cheriostest_tls.c							\
	cheriostest_syscall.c						\
	cheriostest_vm.c						\
	cheriostest_strfcap.c
.if ${MACHINE_ABI:Mpurecap}
SRCS+=	cheriostest_bounds_subobject.c			\
	cheriostest_malloc.c						\
	cheriostest_bounds_varargs.c				\
		cheriostest_sentries.c

#.if ${MK_COMPARTMENT_POLICY} != "no"
#SRCS+=	cheriostest_compartments.c
#CFLAGS.cheriostest_compartments.c+=-ffunction-sections
#COMPARTMENT_POLICY=	${CHERIOSTEST_DIR}/compartments.json
#.endif
.endif

# We currently don't have zlib available on Linux
.if ${OS} == 'FreeBSD'
SRCS+=	cheriostest_zlib.c
.endif

CHERIOSTEST_DIR:=	${.PARSEDIR}
.PATH: ${CHERIOSTEST_DIR}
CFLAGS+=	-I${CHERIOSTEST_DIR}/${MACHINE}

CFLAGS+=	'-DPROG="${PROG}"' '-DPROG_SUFFIX="${PROG:S/^cheriostests//}"'

.if ${MACHINE_ABI:Mpurecap}
SRCS+=	cheriostest_cheriabi.c
SRCS+=	cheriostest_cheriabi_libc.c
SRCS+=	cheriostest_cheriabi_open.c
.endif

#.if ${MACHINE_ABI:Mpurecap} && ${MK_CHERI_CAPREVOKE} == "yes"
#LIBADD+=	cheri_caprevoke
#CFLAGS+=	-DCHERIOSTEST_CHERI_REVOKE_TESTS
#.endif

# This test is broken as written
#SRCS+=	cheriostest_vm_swap.c
#CFLAGS.cheriostest_vm_swap.c+=-Wno-cheri-capability-misuse

.sinclude "${CHERIOSTEST_DIR}/${MACHINE}/Makefile.cheriostest"

# Enable sub-object bounds only in tests specifically designed for them.
CFLAGS.cheriostest_bounds_subobject.c+=-cheri-bounds=subobject-safe

MAN=

.if ${OS} == "FreeBSD"
LIBADD+=	procstat util xo z
.else
# Linux has not libprocstat
LIBADD+=	util xo bsd
.endif

.ifdef CHERIBSD_DYNAMIC_TESTS
CFLAGS+=	-DCHERIBSD_DYNAMIC_TESTS
CFLAGS+=	'-DLIBM_SONAME="libm.so.5"'
# XXXPM: This is hacky but the Makefile will be replaced with cmake files.
CFLAGS+=	-I${.CURDIR}/../libcheriostest_dynamic
LDFLAGS+=	-L${.OBJDIR}/../libcheriostest_dynamic/
DPADD+=	${.OBJDIR}/../libcheriostest_dynamic/libcheriostest_dynamic.so

.if ${OS} == "FreeBSD"
# XXXPM: This is a bit untidy, but we plan to replace the Makefiles
#        with cmake anyways, and so maybe its OK in the interim.
LDADD+=	-Wl,-Bdynamic -lcheriostest_dynamic
.else
LDFLAGS+= -Wl,-rpath=/opt/cheri-os-test/lib/
LDADD+=	-Wl,-Bdynamic -lcheriostest_dynamic -Wl,-Bstatic
.endif
# XXXPM: These fail, but the dynamic linker on some CHERI Linux flavours might
#        be broken.
SRCS+=		cheriostest_fptr_canon.c \
		cheriostest_lazy_bind.c
.else
NO_SHARED?=	YES
.endif

# We don't add these tests on Linux because Musl libc doesn't support ifuncs.
# XXXPM: Check if they are included on CheriBSD as expected
.ifdef CHERIBSD_IFUNC_TESTS && ${OS} != "Linux"
SRCS+=		cheriostest_ifunc.c
.endif

# Both variants exist so we can test with and without libthr's interposition on
# things like signals.
.ifdef CHERIBSD_THREAD_TESTS
CFLAGS+=	-DCHERIBSD_THREAD_TESTS
LIBADD+=	pthread
SRCS+=		cheriostest_tls_threads.c
.endif

.ifdef CHERIBSD_C18N_TESTS
CFLAGS+=	-DCHERIBSD_C18N_TESTS
ELF_FEATURES+=	+cheric18n
.endif

.include <bsd.prog.mk>
