.include <src.opts.mk>

OS!=	uname -s

SRCS=	cheribsdtest.c

#XXX: Commented out test cases that haven't been ported yet
SRCS+=	cheribsdtest_bounds_globals.c					\
	cheribsdtest_util.c \
	cheribsdtest_util_vm.c						\
	cheribsdtest_bounds_globals_x.c					\
	cheribsdtest_bounds_heap.c					\
	cheribsdtest_bounds_stack.c					\
	cheribsdtest_cidcap.c						\
	cheribsdtest_context.c						\
	cheribsdtest_fault.c	\
	cheribsdtest_flag_captured.c					\
	cheribsdtest_fs.c						\
	cheribsdtest_kbounce.c						\
	cheribsdtest_internal.c 					\
	cheribsdtest_ipc.c				\
	cheribsdtest_local_global.c					\
	cheribsdtest_longjmp.c						\
	cheribsdtest_printf.c						\
	cheribsdtest_ptrace.c			\
	cheribsdtest_registers.c		\
	cheribsdtest_sealcap.c			\
	cheribsdtest_signal.c						\
	cheribsdtest_string.c						\
	cheribsdtest_tls.c							\
	cheribsdtest_syscall.c						\
	cheribsdtest_vm.c						\
	cheribsdtest_strfcap.c
.if ${MACHINE_ABI:Mpurecap}
SRCS+=	cheribsdtest_bounds_subobject.c			\
	cheribsdtest_malloc.c						\
	cheribsdtest_bounds_varargs.c				\
		cheribsdtest_sentries.c

#.if ${MK_COMPARTMENT_POLICY} != "no"
#SRCS+=	cheribsdtest_compartments.c
#CFLAGS.cheribsdtest_compartments.c+=-ffunction-sections
#COMPARTMENT_POLICY=	${CHERIBSDTEST_DIR}/compartments.json
#.endif
.endif

# We currently don't have zlib available on Linux
.if ${OS} == 'FreeBSD'
SRCS+=	cheribsdtest_zlib.c
.endif

CHERIBSDTEST_DIR:=	${.PARSEDIR}
.PATH: ${CHERIBSDTEST_DIR}
CFLAGS+=	-I${CHERIBSDTEST_DIR}/${MACHINE}

CFLAGS+=	'-DPROG="${PROG}"' '-DPROG_SUFFIX="${PROG:S/^cheriostests//}"'

.if ${MACHINE_ABI:Mpurecap}
SRCS+=	cheribsdtest_cheriabi.c
SRCS+=	cheribsdtest_cheriabi_libc.c
SRCS+=	cheribsdtest_cheriabi_open.c
.endif

#.if ${MACHINE_ABI:Mpurecap} && ${MK_CHERI_CAPREVOKE} == "yes"
#LIBADD+=	cheri_caprevoke
#CFLAGS+=	-DCHERIBSDTEST_CHERI_REVOKE_TESTS
#.endif

# This test is broken as written
#SRCS+=	cheribsdtest_vm_swap.c
#CFLAGS.cheribsdtest_vm_swap.c+=-Wno-cheri-capability-misuse

.sinclude "${CHERIBSDTEST_DIR}/${MACHINE}/Makefile.cheribsdtest"

# Enable sub-object bounds only in tests specifically designed for them.
CFLAGS.cheribsdtest_bounds_subobject.c+=-cheri-bounds=subobject-safe

MAN=

.if ${OS} == "FreeBSD"
LIBADD+=	procstat util xo z
.else
# Linux has not libprocstat
LIBADD+=	util xo bsd
.endif

.ifdef CHERIBSD_DYNAMIC_TESTS
CFLAGS+=	-DCHERIBSD_DYNAMIC_TESTS
CFLAGS+=	'-DLIBM_SONAME="libm.so.5"'
# XXXPM: This is hacky but the Makefile will be replaced with cmake files.
CFLAGS+=	-I${.CURDIR}/../libcheribsdtest_dynamic
LDFLAGS+=	-L${.OBJDIR}/../libcheribsdtest_dynamic/
DPADD+=	${.OBJDIR}/../libcheribsdtest_dynamic/libcheribsdtest_dynamic.so

LDFLAGS+= -Wl,-rpath=\$$ORIGIN
.if ${OS} == "FreeBSD"
# XXXPM: This is a bit untidy, but we plan to replace the Makefiles
#        with cmake anyways, and so maybe its OK in the interim.
LDADD+=	-Wl,-Bdynamic -lcheribsdtest_dynamic
.else
LDADD+=	-Wl,-Bdynamic -lcheribsdtest_dynamic -Wl,-Bstatic
.endif
# XXXPM: These fail, but the dynamic linker on some CHERI Linux flavours might
#        be broken.
SRCS+=		cheribsdtest_fptr_canon.c \
		cheribsdtest_lazy_bind.c
.else
NO_SHARED?=	YES
.endif

# We don't add these tests on Linux because Musl libc doesn't support ifuncs.
# XXXPM: Check if they are included on CheriBSD as expected
.ifdef CHERIBSD_IFUNC_TESTS && ${OS} != "Linux"
SRCS+=		cheribsdtest_ifunc.c
.endif

# Both variants exist so we can test with and without libthr's interposition on
# things like signals.
.ifdef CHERIBSD_THREAD_TESTS
CFLAGS+=	-DCHERIBSD_THREAD_TESTS
LIBADD+=	pthread
SRCS+=		cheribsdtest_tls_threads.c
.endif

.ifdef CHERIBSD_C18N_TESTS
CFLAGS+=	-DCHERIBSD_C18N_TESTS
ELF_FEATURES+=	+cheric18n
.endif

.include <bsd.prog.mk>
