# Sets the -mabi= compile/link flags on ${target} for the given CHERI ABI.
# ABI: can be "purecap" (default, no flags needed), "hybrid" or "purecap-benchmark".
function(cheriostest_target_set_abi target abi)
    if(abi STREQUAL "hybrid")
        if(CHERIOSTEST_TARGET_ARCH STREQUAL "riscv64")
            target_compile_options(${target} PRIVATE -mabi=lp64d)
            target_link_options(${target} PRIVATE -mabi=lp64d)
        elseif(CHERIOSTEST_TARGET_ARCH STREQUAL "morello")
            target_compile_options(${target} PRIVATE -mabi=aapcs)
            target_link_options(${target} PRIVATE -mabi=aapcs)
        endif()
    elseif(abi STREQUAL "purecap-benchmark")
        if(CHERIOSTEST_TARGET_ARCH STREQUAL "morello")
            target_compile_options(${target} PRIVATE -mabi=purecap-benchmark)
            target_link_options(${target} PRIVATE -mabi=purecap-benchmark)
        else()
            message(FATAL_ERROR "The purecap benchmark ABI is only supported for Morello")
        endif()
    elseif(NOT abi STREQUAL "purecap")
        message(FATAL_ERROR "Unknown ABI for ${target}: ${abi}")
    endif()
endfunction()
